export const styles = {
  heading: {
    float: 'left',
    fontSize: 'xx-small',
    textAlign: 'center',
    width: '100%',
    padding: '0px',
    margin: '0px',
    borderBottom: '1px black solid',
  },
  translationHeading: {
    float: 'left',
    width: '100%',
    position: 'relative',
    overflow: 'hidden',
    padding: '0px',
    margin: '0px',
    borderBottom: '1px black solid',
  },
  translationHeadingL: {
    float: 'left',
    fontSize: 'xx-small',
    textAlign: 'right',
    width: '50%',
    padding: '0px',
    margin: '0px',
    position: 'absolute', 
    bottom: '0',
  },
  translationHeadingR: {
    float: 'right',
    fontSize: 'xx-small',
    textAlign: 'right',
    width: '50%',
    padding: '0px',
    margin: '0px',
  },
  container: {
    position: 'absolute',
    left: '0',
    right: '0',
    height: '100%',
    minHeight: '100%',
  },
  upper: {
    top: '0',
    height: '50%',
    minHeight: '50%',
  },
  editor: {
    width: '100%',
    height: '100%',
    minHeight: '100%',
    overflowY: 'scroll',
    padding: '0 1em',
  },
  lower: {
    bottom: '0',
    height: '50%',
    minHeight: '50%',
    overflowY: 'scroll',
    textAlign: 'center',
  },
  workspace: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'flex-start',
  },
};